/* ─────────────────────────────────────────────────────────────
   CATEGORY CONFIG
   Each category: id, name, identity (for id pillars), desc,
   synonyms (for fill picker), examples, challenges (pillar IDs
   this category is most associated with for challenge relevance)
───────────────────────────────────────────────────────────── */
const CATS = {
  passion:[
    { id:'care',       name:'Care',       identity:'Nurturer',
      desc:'Driven to center wellness and healing for people',
      synonyms:['care and healing','wellness and protection','building safety for people','tending to others','nurturing communities'],
      idSynonyms:['Nurturer','Caregiver','Wellness Champion','Healing Force'],
      examples:'Providing comfort, building safety, tending to relationships',
      challengeAffinity:['harm','scarcity','disconnection'] },

    { id:'creativity', name:'Creativity', identity:'Maker',
      desc:'Motivated by building, imagining, and designing',
      synonyms:['creativity and innovation','building and making','designing new approaches','crafting with purpose','bringing ideas to life'],
      idSynonyms:['Maker','Creator','Innovator','Builder','Visionary Maker'],
      examples:'Designing tools, telling stories that move, crafting solutions',
      challengeAffinity:['resistance','scarcity','invisibility'] },

    { id:'belonging',  name:'Belonging',  identity:'Connector',
      desc:'Driven to create spaces where people feel seen and valued',
      synonyms:['belonging and inclusion','building community','creating spaces of belonging','connecting people','fostering inclusion'],
      idSynonyms:['Connector','Community Builder','Bridge Builder','Unifier'],
      examples:'Forming coalitions, hosting healing events, building culture',
      challengeAffinity:['disconnection','inequity','harm'] },

    { id:'hope',       name:'Hope',       identity:'Visionary',
      desc:'Driven to imagine something better and help others see it',
      synonyms:['hope and possibility','imagining what\'s possible','future thinking','creating new possibilities','envisioning change'],
      idSynonyms:['Visionary','Hope Builder','Possibility Thinker','Dreamer'],
      examples:'Painting possibilities, encouraging others, future-focused work',
      challengeAffinity:['resistance','instability','inequity'] },

    { id:'justice',    name:'Justice',    identity:'Advocate',
      desc:'Driven to make things fair and protect those harmed',
      synonyms:['justice and equity','fighting for fairness','advancing equity','protecting the vulnerable','challenging injustice'],
      idSynonyms:['Advocate','Justice Champion','Equity Leader','Change Fighter'],
      examples:'Challenging bias, organizing for equity, speaking truth to power',
      challengeAffinity:['inequity','harm','resistance'] },

    { id:'growth',     name:'Growth',     identity:'Climber',
      desc:'Motivated by learning and helping others evolve',
      synonyms:['growth and learning','continuous learning','helping others grow','evolving and improving','building capacity'],
      idSynonyms:['Climber','Growth Champion','Learning Leader','Capacity Builder'],
      examples:'Pursuing new skills, deep reflection, transformative programs',
      challengeAffinity:['scarcity','resistance','instability'] },

    { id:'purpose',    name:'Purpose',    identity:'Wayfinder',
      desc:'Driven by a deep sense of calling',
      synonyms:['purpose and calling','mission-driven work','living my calling','working with intention','aligning life and mission'],
      idSynonyms:['Wayfinder','Purpose-Seeker','Mission Leader','Calling-Driven'],
      examples:'Seeking mission alignment, helping others find their why',
      challengeAffinity:['instability','resistance','complexity'] },

    { id:'truth',      name:'Truth',      identity:'Witness',
      desc:'Called to expose what\'s hidden and tell what others won\'t',
      synonyms:['truth and transparency','speaking the truth','exposing hidden realities','truth-telling','holding systems accountable'],
      idSynonyms:['Witness','Truth Teller','Accountability Voice','Story Keeper'],
      examples:'Gathering untold stories, creating records of accountability',
      challengeAffinity:['invisibility','harm','resistance'] },

    { id:'liberation', name:'Liberation', identity:'Liberator',
      desc:'Driven to remove barriers that keep people from thriving',
      synonyms:['liberation and freedom','removing barriers','breaking cycles of harm','building freedom','dismantling what limits people'],
      idSynonyms:['Liberator','Freedom Builder','Barrier Breaker','System Changer'],
      examples:'Breaking cycles of harm, building alternatives to oppressive systems',
      challengeAffinity:['inequity','harm','resistance'] },

    { id:'wisdom',     name:'Wisdom',     identity:'Guide',
      desc:'Grounded in experience, reflection, and shared knowledge',
      synonyms:['wisdom and experience','lived knowledge','ancestral wisdom','deep reflection','mentoring with insight'],
      idSynonyms:['Guide','Wisdom Keeper','Sage','Mentor','Elder Scholar'],
      examples:'Teaching from lived lessons, mentoring through deep listening',
      challengeAffinity:['disconnection','invisibility','scarcity'] },
  ],

  principle:[
    { id:'pr-care',      name:'Care',          identity:'Protector',
      desc:'Centering safety, wellness, and dignity of others',
      synonyms:['care and safety','protecting people','centering wellness','designing with safety','creating supportive spaces'],
      idSynonyms:['Protector','Safety Champion','Wellness Guardian','Care Leader'],
      examples:'Designing with others, preventing burnout, supportive environments',
      challengeAffinity:['harm','scarcity','instability'] },

    { id:'compassion',   name:'Compassion',    identity:'Humanitarian',
      desc:'Striving to reduce suffering and make life easier',
      synonyms:['compassion and kindness','leading with empathy','reducing suffering','designing for those most at risk','radical kindness'],
      idSynonyms:['Humanitarian','Compassion Leader','Empathy Champion','Kindness Keeper'],
      examples:'Leading with kindness, stepping in for others, designing for those most at risk',
      challengeAffinity:['harm','inequity','scarcity'] },

    { id:'accountability',name:'Accountability',identity:'Steward',
      desc:'Taking ownership of actions, outcomes, and growth',
      synonyms:['accountability and ownership','taking responsibility','owning outcomes','building feedback into work','learning from failure'],
      idSynonyms:['Steward','Accountability Champion','Responsibility Leader','Trust Builder'],
      examples:'Owning mistakes, learning from failure, building feedback loops',
      challengeAffinity:['invisibility','resistance','complexity'] },

    { id:'curiosity',    name:'Curiosity',     identity:'Explorer',
      desc:'Ever asking questions and staying open to possibility',
      synonyms:['curiosity and openness','asking better questions','staying open to surprise','exploring new ideas','questioning the status quo'],
      idSynonyms:['Explorer','Curiosity-Seeker','Question Asker','Wonder Keeper'],
      examples:'Experimenting, listening without judgment, looking deeper',
      challengeAffinity:['resistance','complexity','instability'] },

    { id:'humility',     name:'Humility',      identity:'Learner',
      desc:'Staying open and grounded no matter how much you know',
      synonyms:['humility and openness','staying grounded','welcoming feedback','sharing credit','asking for help'],
      idSynonyms:['Learner','Humble Leader','Growth Seeker','Feedback Champion'],
      examples:'Welcoming feedback, asking for help, sharing space and credit',
      challengeAffinity:['resistance','disconnection','complexity'] },

    { id:'courage',      name:'Courage',       identity:'Disrupter',
      desc:'Acting for what\'s right even when it\'s risky',
      synonyms:['courage and conviction','bold action','speaking up','not shrinking','taking brave stands'],
      idSynonyms:['Disrupter','Courageous Leader','Bold Voice','Brave Changemaker'],
      examples:'Naming injustice, trying new ideas, not shrinking when it matters',
      challengeAffinity:['resistance','harm','inequity'] },

    { id:'precision',    name:'Precision',     identity:'Builder',
      desc:'Holding yourself to a high standard of accuracy and care',
      synonyms:['precision and quality','high standards','accuracy and care','intentional work','finishing with excellence'],
      idSynonyms:['Builder','Precision Leader','Quality Champion','Excellence Seeker'],
      examples:'Checking facts, building organized systems, finishing with intention',
      challengeAffinity:['scarcity','complexity','instability'] },

    { id:'refuse-harm',  name:'Refuse Harm',   identity:'Guardian',
      desc:'Refusing to cause harm even when it would be easier',
      synonyms:['refusing harm','do no harm','ethical practice','protecting from harm','responsible action'],
      idSynonyms:['Guardian','Harm Preventer','Ethical Leader','Safety Keeper'],
      examples:'Not overstepping, refusing harmful tactics, ethical practice',
      challengeAffinity:['harm','resistance','inequity'] },

    { id:'integrity',    name:'Integrity',     identity:'Truth-Teller',
      desc:'Staying honest and aligned with values under pressure',
      synonyms:['integrity and honesty','staying aligned with values','speaking truth','authentic action','refusing to perform'],
      idSynonyms:['Truth-Teller','Integrity Leader','Authentic Voice','Values Champion'],
      examples:'Speaking truth when unpopular, refusing to perform, staying consistent',
      challengeAffinity:['resistance','invisibility','harm'] },

    { id:'respect',      name:'Respect',       identity:'Respect-Keeper',
      desc:'Treating everyone with dignity regardless of status',
      synonyms:['respect and dignity','honoring everyone','treating people equally','valuing diverse experiences','dignity-centered work'],
      idSynonyms:['Respect-Keeper','Dignity Champion','Equity Voice','Inclusion Leader'],
      examples:'Honoring boundaries, asking before assuming, speaking to everyone equally',
      challengeAffinity:['inequity','disconnection','harm'] },
  ],

  practice:[
    { id:'building',     name:'Building',      identity:'Builder',
      desc:'Constructing solutions and bringing ideas to life',
      synonyms:['building and engineering','solution development','creating and implementing','prototyping and coding','engineering with care'],
      idSynonyms:['Builder','Engineer','Solution Architect','Creator','Developer'],
      examples:'Software development, coding, prototyping, solution engineering',
      challengeAffinity:['scarcity','complexity','resistance'] },

    { id:'connection',   name:'Connection',    identity:'Connector',
      desc:'Forging relationships, building networks, activating collaboration',
      synonyms:['building connections','relationship building','community networking','mentorship and outreach','activating collaboration'],
      idSynonyms:['Connector','Network Builder','Relationship Strategist','Community Weaver'],
      examples:'Networking, mentoring, community outreach, sponsorship',
      challengeAffinity:['disconnection','instability','scarcity'] },

    { id:'analyzing',    name:'Analyzing',     identity:'Analyst',
      desc:'Revealing patterns, investigating truth, turning data into insight',
      synonyms:['analysis and research','data-driven insight','pattern recognition','research and evaluation','turning data into stories'],
      idSynonyms:['Analyst','Researcher','Data Storyteller','Insight Hunter','Evaluator'],
      examples:'Research, statistics, evaluations, modeling, forecasting',
      challengeAffinity:['invisibility','complexity','scarcity'] },

    { id:'design',       name:'Design',        identity:'Designer',
      desc:'Creating structure, blending function with feeling',
      synonyms:['design and experience','UX and visual design','creating with intention','shaping experiences','art and architecture'],
      idSynonyms:['Designer','Experience Creator','Visual Architect','UX Leader','Creative Director'],
      examples:'Art, architecture, graphic design, UX, illustration, styling',
      challengeAffinity:['scarcity','resistance','complexity'] },

    { id:'education',    name:'Education',     identity:'Educator',
      desc:'Guiding learning, sharing knowledge, supporting understanding',
      synonyms:['education and coaching','teaching and training','curriculum development','facilitating learning','knowledge sharing'],
      idSynonyms:['Educator','Teacher','Learning Architect','Coach','Facilitator'],
      examples:'Teaching, coaching, training, facilitation, curriculum design',
      challengeAffinity:['scarcity','inequity','resistance'] },

    { id:'communication',name:'Communication', identity:'Communicator',
      desc:'Moving ideas, shaping stories, giving voice to what matters',
      synonyms:['communication and storytelling','narrative strategy','shaping stories','giving voice to impact','writing and speaking'],
      idSynonyms:['Communicator','Storyteller','Narrative Strategist','Voice','Journalist'],
      examples:'Writing, speaking, storytelling, marketing, journalism',
      challengeAffinity:['invisibility','resistance','disconnection'] },

    { id:'organizing',   name:'Organizing',    identity:'Organizer',
      desc:'Bringing order to complexity, managing flow and logistics',
      synonyms:['organizing and operations','project management','systems coordination','bringing order to complexity','workflow management'],
      idSynonyms:['Organizer','Operations Lead','Project Manager','Systems Thinker','Coordinator'],
      examples:'Project management, operations, scheduling, team leadership',
      challengeAffinity:['complexity','instability','scarcity'] },

    { id:'protection',   name:'Protection',    identity:'Protector',
      desc:'Enhancing safety, preserving spaces, reducing harm',
      synonyms:['protection and safety','risk management','harm reduction','preserving what matters','emergency response'],
      idSynonyms:['Protector','Safety Leader','Risk Manager','Harm Reducer','Guardian'],
      examples:'Security, emergency response, risk management, compliance',
      challengeAffinity:['harm','instability','inequity'] },

    { id:'healing',      name:'Healing',       identity:'Healer',
      desc:'Mending, restoring, and making space for renewal',
      synonyms:['healing and restoration','counseling and therapy','equity and healing','mindfulness and mentoring','making space for renewal'],
      idSynonyms:['Healer','Counselor','Restoration Leader','Wellness Advocate','Therapist'],
      examples:'Counseling, therapy, equity work, mindfulness, nurturing',
      challengeAffinity:['harm','scarcity','disconnection'] },

    { id:'strategy',     name:'Strategy',      identity:'Strategist',
      desc:'Connecting vision to action, aligning plans with purpose',
      synonyms:['strategy and vision','systems thinking','policy and planning','connecting vision to action','consulting and forecasting'],
      idSynonyms:['Strategist','Visionary','Systems Thinker','Policy Leader','Consultant'],
      examples:'Visioning, policy framing, forecasting, systems thinking',
      challengeAffinity:['complexity','instability','resistance'] },
  ],

  people:[
    { id:'teammates',   name:'Teammates',          identity:null,
      desc:'Side-by-side collaborators who build with you',
      synonyms:['teammates','collaborators','the people I build with','co-creators','partners in the work'],
      examples:'Co-founders, shift partners, project collaborators, fellow organizers' },
    { id:'clients',     name:'Clients',             identity:null,
      desc:'The direct beneficiaries of your work',
      synonyms:['clients','customers','the people I serve','constituents','those who count on me'],
      examples:'Students, patients, residents, shoppers, users, entrepreneurs' },
    { id:'partners',    name:'Partners',            identity:null,
      desc:'External organizations or allies you align with to amplify impact',
      synonyms:['partners','partner organizations','allies and coalitions','external collaborators','mission-aligned partners'],
      examples:'Nonprofits, agencies, community orgs, vendor partners, coalitions' },
    { id:'stakeholders',name:'Stakeholders',        identity:null,
      desc:'Decision-makers whose buy-in shapes what gets done',
      synonyms:['stakeholders','organizational leaders','decision-makers','executives and managers','the people who hold power'],
      examples:'Directors, VPs, board members, elected officials, department heads' },
    { id:'families',    name:'Families',            identity:null,
      desc:'The households whose lives shift because of your work',
      synonyms:['families','households','caregivers and loved ones','the families I serve','home communities'],
      examples:'Parents of students, families of patients, households in your service area' },
    { id:'communities', name:'Communities',         identity:null,
      desc:'The neighborhoods and networks shaped by the people you serve',
      synonyms:['communities','neighborhoods','the communities I serve','local ecosystems','grassroots groups'],
      examples:'Neighborhood residents, cultural communities, civic networks' },
    { id:'mentors',     name:'Mentors & Guides',    identity:null,
      desc:'The people who shaped you — who invested in you before you had a title',
      synonyms:['mentors and guides','the people who shaped me','teachers and elders','those who invested in me','my foundation'],
      examples:'Parents, teachers, coaches, elders, the first person who believed in you' },
    { id:'future',      name:'Future Generations',  identity:null,
      desc:"People who will benefit from your work long after you're gone",
      synonyms:['future generations','the next generation','those who come after','future beneficiaries','people my work will outlast me to reach'],
      examples:'Future students, next-gen leaders, communities shaped by what you built' },
  ],

  products:[
    { id:'tools',      name:'Tools & Resources',    identity:null,
      desc:'Tangible things you made that others pick up and use',
      synonyms:['tools','resources','guides and toolkits','things I built that others use','physical and digital resources'],
      examples:'Dashboards, handbooks, templates, apps, reports, curriculum materials' },
    { id:'systems',    name:'Systems & Processes',  identity:null,
      desc:'The workflows and structures you designed that make work run smoother',
      synonyms:['systems','processes','workflows','structures I put in place','operational improvements'],
      examples:'Onboarding flows, intake processes, safety protocols, scheduling systems' },
    { id:'programs',   name:'Programs & Events',    identity:null,
      desc:'Structured initiatives or learning experiences you designed or led',
      synonyms:['programs','initiatives','workshops and trainings','experiences I designed','structured interventions'],
      examples:'Training programs, fellowships, workshops, town halls, mentoring circles' },
    { id:'culture',    name:'Culture & Moments',    identity:null,
      desc:'Shifts in how people relate or work together — often invisible but lasting',
      synonyms:['culture shifts','cultural moments','team norms I helped create','the way people work now','lasting behavioral change'],
      examples:'Psychological safety, new team rituals, inclusive norms, trust rebuilt after conflict' },
    { id:'knowledge',  name:'Knowledge & Insight',  identity:null,
      desc:'Ideas, analysis, and frameworks that changed how others think or decide',
      synonyms:['knowledge','insights','analysis and findings','ideas that shaped decisions','intellectual contributions'],
      examples:'Research findings, policy briefs, strategic frameworks, evaluation reports' },
    { id:'content',    name:'Content & Stories',    identity:null,
      desc:'Stories, campaigns, and creative work that moved people or shifted understanding',
      synonyms:['content','communications','stories I told','campaigns and media','narratives that shifted perception'],
      examples:'Articles, campaigns, murals, films, speeches, grant narratives, brand work' },
    { id:'outcomes',   name:'Outcomes & Impact',    identity:null,
      desc:'The ripple effects — results that transformed lives, systems, or opportunities',
      synonyms:['outcomes','impact','the difference I made','results that changed things','what changed because I was there'],
      examples:'Funding secured, graduation rates improved, policy changed, trust rebuilt' },
  ],

  places:[
    { id:'classrooms', name:'Schools & Classrooms', identity:null,
      desc:'Learning environments — formal and informal spaces for education and growth',
      synonyms:['schools','classrooms','learning environments','educational settings','campuses and training centers'],
      examples:'K-12 schools, universities, community colleges, training rooms' },
    { id:'offices',    name:'Offices & Organizations', identity:null,
      desc:'Professional environments — workplaces, agencies, and organizational spaces',
      synonyms:['offices','organizations','workplaces','professional settings','agencies and firms'],
      examples:'Corporations, nonprofits, government agencies, startups, consulting firms' },
    { id:'community-spaces', name:'Community Spaces', identity:null,
      desc:'Places where people gather, organize, and support one another',
      synonyms:['community spaces','gathering places','civic spaces','where the community meets','community hubs'],
      examples:'Community centers, churches, libraries, rec centers, town halls' },
    { id:'streets',    name:'Streets & Neighborhoods', identity:null,
      desc:'On-the-ground spaces of everyday life — where impact is most direct',
      synonyms:['neighborhoods','on the ground','streets and blocks','where people actually live','the community'],
      examples:'Neighborhoods, housing developments, parks, storefronts, playgrounds' },
    { id:'healthcare', name:'Clinics & Care Settings', identity:null,
      desc:'Health and wellness environments — places of healing and recovery',
      synonyms:['hospitals','clinics','care settings','healthcare environments','places of healing'],
      examples:'Hospitals, community health centers, mental health clinics, shelters' },
    { id:'digital',    name:'Digital Spaces',    identity:null,
      desc:'Online platforms and virtual environments where your work lives',
      synonyms:['digital spaces','online platforms','virtual environments','digital communities','the internet'],
      examples:'Social media, apps, virtual classrooms, online communities, remote workplaces' },
    { id:'field',      name:'Field & Sites',     identity:null,
      desc:'On-location environments — job sites, retail floors, outdoor spaces',
      synonyms:['field sites','job sites','on location','the field','where the real work happens'],
      examples:'Construction sites, labs, retail floors, farms, event venues, restaurants' },
  ],
};
